name: Pull, Scan, and Generate Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Pull Nginx Docker image
        run: |
          docker pull nginx:latest
          ls -la
          pwd
          

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'nginx:latest'  # Scanning the pulled Nginx image
          format: 'table'
          template: '/home/runner/work/trivy/trivy/html.tpl'  # Path to your template file
          # output: 'trivy-report.html'
          exit-code: '1'  # Fail the job if vulnerabilities are found
          ignore-unfixed: true
          vuln-type: 'os,library'
          cache: 'true'
          severity: 'CRITICAL,HIGH,LOW'

      - name: Display Trivy report
        run: |
          ls -la
          cat trivy-report.html  # Print the report to the console for debugging

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.html
