name: Pull, Scan, and Generate Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Pull Nginx Docker image
        run: |
          docker pull nginx:latest  # Use a known vulnerable image for testing
          ls -la
          pwd
          
      - name: Run Trivy Vulnerability Scanner
        run: |
          trivy image --format template --template "@html.tpl" --vuln-type os,library -o trivy-report.html nginx:latest

      - name: Display Trivy report
        run: |
          ls -la
          cat trivy-report.html  # Print the report to the console for debugging

      - name: Upload Trivy report
        uses: actions/upload-artifact@v4  # Use v2 for upload-artifact
        with:
          name: trivy-report
          path: trivy-report.html
